const LocalImages = {
  sent: require('../../assets/images/tick.png'),
  read: require('../../assets/images/read.png'),
  help: require('../../assets/images/help.png'),
  logo: require('../../assets/images/Logo.png'),
  bell: require('../../assets/images/bell.png'),
  clock: require('../../assets/images/clock.png'),
  search: require('../../assets/images/search.png'),
  qrCode: require('../../assets/images/qrcode.png'),
  logout: require('../../assets/images/logout.png'),
  options: require('../../assets/images/options.png'),
  backbutton: require('../../assets/images/back.png'),
  message: require('../../assets/images/message.png'),
  stats: require('../../assets/images/dashboard.png'),
  account: require('../../assets/images/account.png'),
  phone: require('../../assets/images/telephone.png'),
  sendButton: require('../../assets/images/send.png'),
  defaultUser: require('../../assets/images/user.png'),
  arrow_Down: require('../../assets/images/arrow_Down.png'),
  background: require('../../assets/images/Background.png'),
  video_Camera: require('../../assets/images/video_camera.png'),
  logoContainer: require('../../assets/images/LogoBackground.png'),
};

export default LocalImages;
