const Strings = {
  faq: 'FAQ',
  next: 'Next',
  help: 'help',
  users: 'Users',
  chats: 'Chats',
  online: 'Online',
  status: 'Status',
  backup: 'Backup',
  history: 'History',
  account: 'Account',
  signOut: 'Signout',
  privacy: 'Privacy',
  message: 'Message',
  search: 'Search...',
  appname: 'SwipeText',
  inbox: 'RecentChats',
  security: 'Security',
  updateImage: 'Update',
  removeImage: 'Remove',
  addImage: 'Add Image',
  chatRooms: 'Chatrooms',
  wallpaper: 'wallpaper',
  enterName: 'Enter Name',
  contactus: 'Contact us',
  addDetails: 'Add Details',
  enterText: 'Enter Message',
  Resend_Code: 'Resend Code',
  contactList: 'Contact List',
  yourProfile: 'Your Profile',
  editDetails: 'Edit Details',
  networkUsage: 'Network Usage',
  notification: 'Notifications',
  enterSMSCode: 'Enter SMS Code',
  imageCancel: 'Image Selection Cancelled',
  welcomeToWhatsapp: 'Welcome To Whatsapp',
  deletedMessage: 'This Message was Deleted',
  dataAndStorageUsage: 'Data and storage usage',
  phoneNumberError: 'Phone Number must be 10 digit long',
};

export default Strings;
